source_directories:
    - ~/Documents
    - ~/Downloads
    - ~/Pictures
    - ~/Projects
    - ~/.ssh
repositories:
    - path: /media/kostya/data/backup
      label: hdd
exclude_patterns:
    - '**/node_modules'
keep_weekly: 4
